# Generated by Django 5.0.6 on 2024-10-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankruft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bankruft', models.BooleanField(default=False)),
            ],
        ),
    ]
